//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by WebApiProxyGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//#region angular imports
import { Proxy } from '../../Commons/Services/proxy';
import { Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { map } from 'rxjs/operators';
import { ValidateTokenIn } from '../MethodParameters/validateTokenIn';
import { ValidateTokenOut } from '../MethodParameters/validateTokenOut';
//#endregion


@Injectable()
export class TokenService {

    constructor(private proxy: Proxy) { 
	}

	

	validateToken(input:ValidateTokenIn): Observable<ValidateTokenOut> {
		let response = this.proxy.executePost("Authentication/ValidateToken", input,null).pipe(map((resp)=>this.mapValidateTokenDataResponse(resp)));
		return response;
	}
	 
	mapValidateTokenDataResponse(info: any): ValidateTokenOut {
		let result = <ValidateTokenOut>info;
		return result;
	}

}
