//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by WebApiProxyGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


import * as moment from 'moment';
import { BaseOut } from '../../Commons/Classes/baseOut';

export class ValidateTokenIn extends BaseOut {
 
	public $type: string = "MethodParameters.Administration.Authentication.ValidateTokenIn, MethodParameters";
	   
	public token:string;



}
