//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by WebApiProxyGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//#region angular imports

import { Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { map } from 'rxjs/operators';
//#endregion

import { Proxy } from "../../../../Commons/Services/proxy";
import { GetServicesIn } from "../MethodParameters/getServicesIn";
import { GetServicesOut } from "../MethodParameters/getServicesOut";
import { UpdateServiceIn } from "../MethodParameters/updateServiceIn";
import { UpdateServiceOut } from "../MethodParameters/updateServiceOut";


@Injectable()
export class ServiceService {

    constructor(private proxy: Proxy) { 
	}

	

	getServices(input:GetServicesIn): Observable<GetServicesOut> {
		let response = this.proxy.executePost("Service/GetServices", input,null).pipe(map((resp)=>this.mapGetServicesDataResponse(resp)));
		return response;
	}
	 
	mapGetServicesDataResponse(info: any): GetServicesOut {
		let result = <GetServicesOut>info;
		return result;
	}

	updateService(input:UpdateServiceIn): Observable<UpdateServiceOut> {
		let response = this.proxy.executePost("Service/UpdateService", input,null).pipe(map((resp)=>this.mapUpdateServiceDataResponse(resp)));
		return response;
	}
	 
	mapUpdateServiceDataResponse(info: any): UpdateServiceOut {
		let result = <UpdateServiceOut>info;
		return result;
	}

}
