//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by WebApiProxyGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import * as moment from 'moment';

export class ActionsByRole  {
 
	public $type: string = "SD.Entities.ActionsByRole, SD.Entities";
	   
	public aseID:number;

	public rolID:number;

}