//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by WebApiProxyGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import * as moment from 'moment';

export class Agreement  {
 
	public $type: string = "SD.Entities.Agreement, SD.Entities";
	   
	public agrID:number;

	public agr_code:string;

	public agr_document_number:string;

	public agr_name:string;

	public agr_flexible_fee:boolean;

	public agr_status:string;

	public agr_creation_date:Date | moment.Moment;

	public agr_user_creation:number;

	public agr_modification_date:Date | moment.Moment;

	public agr_user_modification:number;


}
