//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by WebApiProxyGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import * as moment from 'moment';

export class Audit  {

    public aud_idRequest:number;

	public aud_transaction:string;

	public aud_status:string;

	public aud_date: string;

}
