//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by WebApiProxyGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import * as moment from 'moment';

export class Campaign  {
 
	public $type: string = "SD.Entities.Campaign, SD.Entities";
	   
	public camID:number;

	public cam_code_campaign:string;

	public cam_name_campaign:string;

	public cam_code_origin_entity:string;

	public cam_sales_force:string;

	public cam_start_date:Date | moment.Moment;

	public cam_end_date:Date | moment.Moment;

	public cam_closing_date:Date | moment.Moment;

	public cam_status:string;

	public cam_creation_date:Date | moment.Moment;

	public cam_user_creation:number;

	public cam_modification_date:Date | moment.Moment;

	public cam_user_modification:number;

}
