//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by WebApiProxyGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import * as moment from 'moment';

export class Client  {
 
	public $type: string = "SD.Entities.Client, SD.Entities";
	   
	public cliID:number;

	public oblID:number;

	public cli_document_type:string;

	public cli_document_number:string;

	public cli_first_name:string;

	public cli_second_name:string;

	public cli_first_surname:string;

	public cli_second_surname:string;

	public cli_full_name:string;

	public cli_mobile_1:number;

	public cli_mobile_2:number;

	public cli_email_1:string;

	public cli_email_2:string;

	public cli_birthdate:Date | moment.Moment;

	public cli_expedition_date: Date | moment.Moment;
}
