//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by WebApiProxyGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


import * as moment from 'moment';
import { Services } from './services';
import { Roles } from './roles';

export class HiredServices  {
 
	public $type: string = "SD.Entities.HiredServices, SD.Entities";
	   
	public hirID:number;

	public service:Services;

	public ubeID:number;

	public rol:Roles;

	public hir_status:string;

	public hir_creation_date:Date | moment.Moment;

	public hir_user_creation:number;

	public hir_modification_date:Date | moment.Moment;

	public hir_user_modification:number;



}
