import * as moment from 'moment';

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by WebApiProxyGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class HistoricStep {

	public $type: string = "SD.Entities.Offer, SD.Entities";

	public stepID: string;

	public hisStep_advisory_code: number;

	public hisStep_step_date: Date | moment.Moment;
}