//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by WebApiProxyGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import * as moment from 'moment';
import { ActionsByRole } from './actionsByRole';

export class Roles  {
 
	public $type: string = "SD.Entities.Roles, SD.Entities";
	   
	public rolID:number;

	public serID:number;

	public rol_name:string;

	public actionsByRole: Array<ActionsByRole>;

}