//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by WebApiProxyGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import * as moment from 'moment';
import { Roles } from './roles';

export class Services  {
 
	public $type: string = "SD.Entities.Services, SD.Entities";
	   
	public serID:number;

	public ser_nombre:string;

	public ser_status:string;

	public roles:Array<Roles>;
	
}