//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by WebApiProxyGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
export class Step  {
 
	public $type: string = "SD.Entities.Step, SD.Entities";
	   
    public steID:string;

    public ste_description:string;

    public ste_next:string;

    public ste_resumes:boolean;

}
