export const ROUTES_CATALOGS = [
    {NAME: 'Tipo Cuenta', VALUE: 'Tbl_AccountBanksType'},
    {NAME: 'Grupo al que Pertenece', VALUE: 'Tbl_AffnityGroup'},
    {NAME: 'Bancos', VALUE: 'Tbl_Banks'},
    {NAME: 'Periodos Facturación', VALUE: 'Tbl_BillingCycles'},
    {NAME: 'BIN', VALUE: 'Tbl_BIN'},
    {NAME: 'Actividad economica', VALUE: 'Tbl_BusinessActivity'},
    {NAME: 'Actividad', VALUE: 'Tbl_BusinessName'},
    {NAME: 'Canal', VALUE: 'Tbl_Channel'},
    {NAME: 'CIIU', VALUE: 'Tbl_Ciiu'},
    {NAME: 'CiudadSIIf', VALUE: 'Tbl_CitySIIF'},
    {NAME: 'Tipo Contrato', VALUE: 'Tbl_ContractType'},
    {NAME: 'PaisSIFF', VALUE: 'Tbl_CountrySIIF'},
    {NAME: 'Moneda', VALUE: 'Tbl_Currency'},
    {NAME: 'Operaciones', VALUE: 'Tbl_CurrencyOperationTypes'},
    {NAME: 'Informacion Catalogos', VALUE: 'Tbl_DatoCatalogo'},
    {NAME: 'DepartamentoSIIF', VALUE: 'Tbl_DepartamentSIIF'},
    {NAME: 'Departamento', VALUE: 'Tbl_Department'},
    {NAME: 'ESP', VALUE: 'TBL_ESP'},
    {NAME: 'Genero', VALUE: 'Tbl_Gender'},
    {NAME: 'Estrato', VALUE: 'Tbl_HousingStratum'},
    {NAME: 'Tipo Vivienda', VALUE: 'Tbl_HousingType'},
    {NAME: 'Tipo Identificación', VALUE: 'Tbl_IdentificationType'},
    {NAME: 'Tipo Identificación SIIF', VALUE: 'Tbl_IdentificationTypeSIIF'},
    {NAME: 'Fuente Ingreso', VALUE: 'Tbl_IncomeSource'},
    {NAME: 'Estado Civil', VALUE: 'Tbl_MaritalStatus'},
    {NAME: 'Municipio', VALUE: 'Tbl_Municipality'},
    {NAME: 'Nacionalidad', VALUE: 'Tbl_Nationality'},
    {NAME: 'Ocupacion', VALUE: 'Tbl_Occupation'},
    {NAME: 'Ocupacion SIIF', VALUE: 'Tbl_OccupationSIIF'},
    {NAME: 'Tipo Persona', VALUE: 'Tbl_PersonType'},
    {NAME: 'Tipo Producto', VALUE: 'Tbl_ProductType'},
    {NAME: 'Profesion SIIF', VALUE: 'Tbl_ProfessionSIIF'},
    {NAME: 'Tipo Propiedad', VALUE: 'Tbl_PropertyType'},
    {NAME: 'Relacion', VALUE: 'Tbl_RelationShip'},
    {NAME: 'Tipo Relacion', VALUE: 'Tbl_RelationType'},
    {NAME: 'Nivel Educativo', VALUE: 'Tbl_SchoolsLevel'},
    {NAME: 'Termino lbza', VALUE: 'Tbl_Termlbza'},
    {NAME: 'Tipo Operacion', VALUE: 'Tbl_TypeofOperation'},
    {NAME: 'Tipo Vehiculo', VALUE: 'Tbl_VehicleType'},
];

