//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by WebApiProxyGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import * as moment from 'moment';
import { BaseIn } from '../../../../Commons/Classes/baseIn';
import { Service } from '../../../../Commons/Entities/service';

export class UpdateServiceIn extends BaseIn {
 
	public $type: string = "MethodParameters.Administration.Service.UpdateServiceIn, MethodParameters";
	   
	public service:Service;



}
